# Code Generated by Sidekick is for learning and experimentation purposes only.
import pandas as pd

# Load both files (adjust filenames and sheet names as needed)
header_df = pd.read_excel("C:\\Users\\kulareddy\\Downloads\\header b0.xlsx")
line_df = pd.read_excel("C:\\Users\\kulareddy\\Downloads\\line transformed.xlsx")

# Filter line_df where SubscriptionNumber exists in header_df
filtered_df = line_df[line_df['SubscriptionNumber'].isin(header_df['SubscriptionNumber'])]

# Save the result to a new Excel file
filtered_df.to_excel('line_filtered.xlsx', index=False)
